// core/components/TextField.vue
<template>
  <input class="ns-textfield" type="text" :value="text" @input="onInput" @keyup.enter="onSubmit" />
</template>

<script setup lang="ts">
defineOptions({ name: 'TextField' });
defineProps<{ text?: string }>();
const emit = defineEmits<{ (e: 'update:text', v: string): void; (e: 'submit', v: string): void }>();
function onInput(e: Event) { emit('update:text', (e.target as HTMLInputElement).value); }
function onSubmit(e: KeyboardEvent) { emit('submit', (e.target as HTMLInputElement).value); }
</script>

<style scoped>
.ns-textfield { width: 100%; padding: 6px 8px; }
</style>

// angular/components/text-field.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
	selector: 'TextField, textfield',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<input
			class="ns-textfield"
			type="text"
			[value]="text ?? ''"
			(input)="onInput($event)"
			(keyup.enter)="onSubmit($event)"
		/>
	`,
	styles: [
		`
			.ns-textfield {
				width: 100%;
				padding: 6px 8px;
			}
		`,
	],
})
export class TextFieldComponent {
	@Input() text?: string;
	@Output() textChange = new EventEmitter<string>();
	@Output() submit = new EventEmitter<string>();

	onInput(e: Event) {
		this.textChange.emit((e.target as HTMLInputElement).value);
	}

	onSubmit(e: KeyboardEvent) {
		this.submit.emit((e.target as HTMLInputElement).value);
	}
}
