// core/components/WebView.vue
<template>
  <iframe class="ns-webview" :src="src" v-if="src"></iframe>
  <div class="ns-webview" v-else><slot /></div>
</template>

<script setup lang="ts">
defineOptions({ name: 'WebView' });
defineProps<{ src?: string }>();
</script>

<style scoped>
.ns-webview { width: 100%; height: 100%; border: none; }
</style>

// angular/components/web-view.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
	selector: 'WebView, webview',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [CommonModule],
	template: `
		<iframe class="ns-webview" *ngIf="src; else projected" [src]="src"></iframe>
		<ng-template #projected><div class="ns-webview"><ng-content></ng-content></div></ng-template>
	`,
	styles: [
		`
			.ns-webview {
				width: 100%;
				height: 100%;
				border: none;
			}
		`,
	],
})
export class WebViewComponent {
	@Input() src?: string;
}
