// angular/components/date-picker.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
	selector: 'DatePicker, datepicker',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `<input class="ns-datepicker" type="date" [value]="valueStr" (input)="onInput($event)" />`,
	styles: [
		`
			.ns-datepicker {
				padding: 6px 8px;
			}
		`,
	],
})
export class DatePickerComponent {
	@Input() date?: string | Date;
	@Output() dateChange = new EventEmitter<string | Date>();
	@Output() change = new EventEmitter<string | Date>();

	get valueStr(): string {
		if (!this.date) return '';
		const d = typeof this.date === 'string' ? new Date(this.date) : this.date;
		if (Number.isNaN(d.getTime())) return '';
		const pad = (n: number) => (n < 10 ? `0${n}` : String(n));
		return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
	}

	onInput(e: Event) {
		const v = (e.target as HTMLInputElement).value;
		this.dateChange.emit(v);
		this.change.emit(v);
	}
}

// core/components/DatePicker.vue
<template>
  <input class="ns-datepicker" type="date" :value="valueStr" @input="onInput" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
defineOptions({ name: 'DatePicker' });
const props = defineProps<{ date?: string | Date }>();
const emit = defineEmits<{ (e: 'update:date', v: string | Date): void; (e: 'change', v: string | Date): void }>();

function pad(n: number) { return n < 10 ? `0${n}` : String(n); }
const valueStr = computed(() => {
  if (!props.date) return '';
  const d = typeof props.date === 'string' ? new Date(props.date) : props.date;
  if (isNaN(d.getTime())) return '';
  return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
});
function onInput(e: Event) {
  const v = (e.target as HTMLInputElement).value;
  emit('update:date', v);
  emit('change', v);
}
</script>

<style scoped>
.ns-datepicker { padding: 6px 8px; }
</style>
