// angular/components/list-picker.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
	selector: 'ListPicker, listpicker',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [CommonModule],
	template: `
		<select class="ns-listpicker" [value]="selectedIndex ?? 0" (change)="onChange($event)">
			<option *ngFor="let item of items; let i = index" [value]="i">{{ item }}</option>
		</select>
	`,
	styles: [
		`
			.ns-listpicker {
				padding: 6px 8px;
			}
		`,
	],
})
export class ListPickerComponent {
	@Input({ required: true }) items: string[] = [];
	@Input() selectedIndex?: number;
	@Output() selectedIndexChange = new EventEmitter<number>();
	@Output() change = new EventEmitter<number>();

	onChange(e: Event) {
		const v = Number((e.target as HTMLSelectElement).value);
		this.selectedIndexChange.emit(v);
		this.change.emit(v);
	}
}

// core/components/ListPicker.vue
<template>
  <select class="ns-listpicker" :value="selectedIndex" @change="onChange">
    <option v-for="(item, i) in items" :key="i" :value="i">{{ item }}</option>
  </select>
</template>

<script setup lang="ts">
defineOptions({ name: 'ListPicker' });
const props = defineProps<{ items: string[]; selectedIndex?: number }>();
const emit = defineEmits<{ (e: 'update:selectedIndex', v: number): void; (e: 'change', v: number): void }>();

function onChange(e: Event) {
  const v = Number((e.target as HTMLSelectElement).value);
  emit('update:selectedIndex', v);
  emit('change', v);
}
</script>

<style scoped>
.ns-listpicker { padding: 6px 8px; }
</style>
