// angular/components/navigation-button.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
	selector: 'NavigationButton, navigationbutton',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [CommonModule],
	template: `
		<button class="ns-navbutton" (click)="onClick($event)">
			<ng-content></ng-content>
			<ng-container *ngIf="text">{{ text }}</ng-container>
		</button>
	`,
	styles: [
		`
			.ns-navbutton {
				background: transparent;
				border: none;
				color: inherit;
				cursor: pointer;
				padding: 8px;
			}
		`,
	],
})
export class NavigationButtonComponent {
	@Input() text?: string;
	@Output() tap = new EventEmitter<MouseEvent>();

	onClick(e: MouseEvent) {
		this.tap.emit(e);
		if ((this.tap as any).observers?.length) return;
		if (window?.history?.back) window.history.back();
	}
}

// core/components/NavigationButton.vue
<template>
  <button class="ns-navbutton" @click="onClick">
    <slot>{{ text }}</slot>
  </button>
</template>

<script setup lang="ts">
import { getCurrentInstance } from 'vue';
defineProps<{ text?: string }>();
const emit = defineEmits<{ (e: 'tap', evt: MouseEvent): void }>();
defineOptions({ name: 'NavigationButton' });

function onClick(e: MouseEvent) {
  emit('tap', e);
  // 默认行为：若未监听 tap，则尝试返回上一页
  const inst = getCurrentInstance();
  const hasTapListener = !!(inst?.vnode?.props && (inst.vnode.props as any).onTap);
  if (!hasTapListener) {
    const router = (inst?.appContext?.config?.globalProperties as any)?.$router;
    if (router?.go) router.go(-1);
    else if (window?.history?.back) window.history.back();
  }
}
</script>

<style scoped>
.ns-navbutton { background: transparent; border: none; color: inherit; cursor: pointer; padding: 8px; }
</style>
