// angular/components/search-bar.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
	selector: 'SearchBar, searchbar',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<div class="ns-searchbar">
			<input type="search" [value]="text ?? ''" (input)="onInput($event)" (keyup.enter)="onSubmit($event)" />
		</div>
	`,
	styles: [
		`
			.ns-searchbar input {
				width: 100%;
				padding: 6px 8px;
			}
		`,
	],
})
export class SearchBarComponent {
	@Input() text?: string;
	@Output() textChange = new EventEmitter<string>();
	@Output() submit = new EventEmitter<string>();

	onInput(e: Event) {
		this.textChange.emit((e.target as HTMLInputElement).value);
	}

	onSubmit(e: KeyboardEvent) {
		this.submit.emit((e.target as HTMLInputElement).value);
	}
}

// core/components/SearchBar.vue
<template>
  <div class="ns-searchbar">
    <input type="search" :value="text" @input="onInput" @keyup.enter="onSubmit" />
  </div>
  
</template>

<script setup lang="ts">
defineOptions({ name: 'SearchBar' });
const props = defineProps<{ text?: string }>();
const emit = defineEmits<{ (e: 'update:text', v: string): void; (e: 'submit', v: string): void }>();
function onInput(e: Event) {
  emit('update:text', (e.target as HTMLInputElement).value);
}
function onSubmit(e: KeyboardEvent) {
  emit('submit', (e.target as HTMLInputElement).value);
}
</script>

<style scoped>
.ns-searchbar input { width: 100%; padding: 6px 8px; }
</style>
