// angular/components/slider.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
	selector: 'Slider, slider',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<input
			class="ns-slider"
			type="range"
			[min]="min ?? 0"
			[max]="max ?? 100"
			[step]="step ?? 1"
			[value]="value ?? 0"
			(input)="onInput($event)"
		/>
	`,
	styles: [
		`
			.ns-slider {
				width: 100%;
			}
		`,
	],
})
export class SliderComponent {
	@Input() value?: number;
	@Input() min?: number;
	@Input() max?: number;
	@Input() step?: number;

	@Output() valueChange = new EventEmitter<number>();
	@Output() change = new EventEmitter<number>();

	onInput(e: Event) {
		const v = Number((e.target as HTMLInputElement).value);
		this.valueChange.emit(v);
		this.change.emit(v);
	}
}

// core/components/Slider.vue
<template>
  <input class="ns-slider" type="range" :min="min" :max="max" :step="step" :value="value" @input="onInput" />
</template>

<script setup lang="ts">
defineOptions({ name: 'Slider' });
const props = defineProps<{ value?: number; min?: number; max?: number; step?: number }>();
const emit = defineEmits<{ (e: 'update:value', v: number): void; (e: 'change', v: number): void }>();
function onInput(e: Event) {
  const v = Number((e.target as HTMLInputElement).value);
  emit('update:value', v);
  emit('change', v);
}
</script>

<style scoped>
.ns-slider { width: 100%; }
</style>
