// angular/components/text-view.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
	selector: 'TextView, textview',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `<textarea class="ns-textview" [value]="text ?? ''" (input)="onInput($event)"></textarea>`,
	styles: [
		`
			.ns-textview {
				width: 100%;
				min-height: 80px;
				padding: 6px 8px;
			}
		`,
	],
})
export class TextViewComponent {
	@Input() text?: string;
	@Output() textChange = new EventEmitter<string>();
	@Output() change = new EventEmitter<string>();

	onInput(e: Event) {
		const v = (e.target as HTMLTextAreaElement).value;
		this.textChange.emit(v);
		this.change.emit(v);
	}
}

// core/components/TextView.vue
<template>
  <textarea class="ns-textview" :value="text" @input="onInput"></textarea>
</template>

<script setup lang="ts">
defineOptions({ name: 'TextView' });
defineProps<{ text?: string }>();
const emit = defineEmits<{ (e: 'update:text', v: string): void; (e: 'change', v: string): void }>();
function onInput(e: Event) {
  const v = (e.target as HTMLTextAreaElement).value;
  emit('update:text', v);
  emit('change', v);
}
</script>

<style scoped>
.ns-textview { width: 100%; min-height: 80px; padding: 6px 8px; }
</style>
