// angular/components/time-picker.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
	selector: 'TimePicker, timepicker',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `<input class="ns-timepicker" type="time" [value]="time ?? ''" (input)="onInput($event)" />`,
	styles: [
		`
			.ns-timepicker {
				padding: 6px 8px;
			}
		`,
	],
})
export class TimePickerComponent {
	@Input() time?: string;
	@Output() timeChange = new EventEmitter<string>();
	@Output() change = new EventEmitter<string>();

	onInput(e: Event) {
		const v = (e.target as HTMLInputElement).value;
		this.timeChange.emit(v);
		this.change.emit(v);
	}
}

// core/components/TimePicker.vue
<template>
  <input class="ns-timepicker" type="time" :value="valueStr" @input="onInput" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
defineOptions({ name: 'TimePicker' });
const props = defineProps<{ time?: string }>();
const emit = defineEmits<{ (e: 'update:time', v: string): void; (e: 'change', v: string): void }>();

const valueStr = computed(() => props.time ?? '');
function onInput(e: Event) {
  const v = (e.target as HTMLInputElement).value;
  emit('update:time', v);
  emit('change', v);
}
</script>

<style scoped>
.ns-timepicker { padding: 6px 8px; }
</style>
